export const TRACKS = [
  {
    id: 'provisoire',
    name: 'Provisoire',
    subtitle: 'Rwanda Driving Test',
    description: "Rwanda's provisional driving licence theory exam, extracted from the official question bank.",
    examTotal: 20,
    passMark: 12, // matches the real exam's 60% pass mark
    hasLanguages: true,
    hasImages: true,
    hasLawNotice: true,
  },
  {
    id: 'it-networking',
    name: 'Networking',
    subtitle: 'Network+ style',
    description: 'OSI/TCP-IP models, IP addressing, routing & switching, protocols, wireless, troubleshooting.',
    examTotal: 20,
    passMark: 14, // ~70%, a common certification-style pass bar
    hasLanguages: false,
    hasImages: false,
    hasLawNotice: false,
    references: [
      { label: 'IANA Service Name and Transport Protocol Port Number Registry', url: 'https://www.iana.org/assignments/service-names-port-numbers' },
      { label: 'RFC 1918 - Address Allocation for Private Internets', url: 'https://www.rfc-editor.org/rfc/rfc1918' },
      { label: 'RFC 2131 - Dynamic Host Configuration Protocol (DHCP)', url: 'https://www.rfc-editor.org/rfc/rfc2131' },
      { label: 'CompTIA Network+ (N10-009) official exam objectives', url: 'https://www.comptia.org/certifications/network' },
    ],
  },
  {
    id: 'it-cybersecurity',
    name: 'Cybersecurity',
    subtitle: 'Security+ style',
    description: 'CIA triad, malware types, social engineering, cryptography, access control, common attacks.',
    examTotal: 20,
    passMark: 14,
    hasLanguages: false,
    hasImages: false,
    hasLawNotice: false,
    references: [
      { label: 'OWASP Top 10', url: 'https://owasp.org/Top10/' },
      { label: 'NIST Cybersecurity Framework', url: 'https://www.nist.gov/cyberframework' },
      { label: 'NIST Glossary (CIA triad, threat/vulnerability/exploit definitions)', url: 'https://csrc.nist.gov/glossary' },
      { label: 'CompTIA Security+ (SY0-701) official exam objectives', url: 'https://www.comptia.org/certifications/security' },
    ],
  },
  {
    id: 'it-helpdesk',
    name: 'IT Helpdesk / Support',
    subtitle: 'A+ style',
    description: 'Hardware, OS troubleshooting, ports/connectors, customer service, ticketing & triage.',
    examTotal: 20,
    passMark: 14,
    hasLanguages: false,
    hasImages: false,
    hasLawNotice: false,
    references: [
      { label: 'CompTIA A+ (220-1101/1102) official exam objectives', url: 'https://www.comptia.org/certifications/a' },
      { label: 'Microsoft Learn - Windows client documentation', url: 'https://learn.microsoft.com/windows/' },
      { label: 'IANA Service Name and Transport Protocol Port Number Registry', url: 'https://www.iana.org/assignments/service-names-port-numbers' },
    ],
  },
  {
    id: 'it-software',
    name: 'Software & Programming',
    subtitle: 'Fundamentals',
    description: 'Programming basics, OOP, SDLC/Agile, Git, databases, data structures, web & API concepts.',
    examTotal: 20,
    passMark: 14,
    hasLanguages: false,
    hasImages: false,
    hasLawNotice: false,
    references: [
      { label: 'MDN Web Docs (HTML, CSS, JavaScript, HTTP)', url: 'https://developer.mozilla.org/' },
      { label: 'Git official documentation', url: 'https://git-scm.com/doc' },
      { label: 'Scrum Guide (scrum.org)', url: 'https://scrumguides.org/' },
    ],
  },
  {
    id: 'it-cloud',
    name: 'Cloud Computing',
    subtitle: 'AWS / Azure / GCP fundamentals',
    description: 'Service models, deployment models, core AWS/Azure/GCP services, networking, cost, and security in the cloud.',
    examTotal: 20,
    passMark: 14,
    hasLanguages: false,
    hasImages: false,
    hasLawNotice: false,
    references: [
      { label: 'AWS - What Is Cloud Computing?', url: 'https://aws.amazon.com/what-is-cloud-computing/' },
      { label: 'Microsoft Learn - Azure fundamentals', url: 'https://learn.microsoft.com/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/' },
      { label: 'Google Cloud documentation', url: 'https://cloud.google.com/docs' },
      { label: 'NIST SP 800-145 - The NIST Definition of Cloud Computing', url: 'https://csrc.nist.gov/pubs/sp/800/145/final' },
    ],
  },
  {
    id: 'it-databases',
    name: 'Databases & SQL',
    subtitle: 'Relational & NoSQL fundamentals',
    description: 'Relational modeling, SQL queries, normalization, transactions, indexing, and NoSQL database concepts.',
    examTotal: 20,
    passMark: 14,
    hasLanguages: false,
    hasImages: false,
    hasLawNotice: false,
    references: [
      { label: 'PostgreSQL official documentation', url: 'https://www.postgresql.org/docs/' },
      { label: 'MySQL official documentation', url: 'https://dev.mysql.com/doc/' },
      { label: 'Microsoft SQL Server / T-SQL documentation', url: 'https://learn.microsoft.com/sql/t-sql/language-reference' },
      { label: 'MongoDB Manual', url: 'https://www.mongodb.com/docs/manual/' },
    ],
  },
  {
    id: 'it-sysadmin',
    name: 'System Administration',
    subtitle: 'Windows & Linux',
    description: 'Active Directory, Group Policy, PowerShell, Linux administration, virtualization, and server infrastructure.',
    examTotal: 20,
    passMark: 14,
    hasLanguages: false,
    hasImages: false,
    hasLawNotice: false,
    references: [
      { label: 'Microsoft Learn - Windows Server documentation', url: 'https://learn.microsoft.com/windows-server/' },
      { label: 'Microsoft Learn - Active Directory Domain Services', url: 'https://learn.microsoft.com/windows-server/identity/ad-ds/active-directory-domain-services' },
      { label: 'Microsoft Learn - PowerShell documentation', url: 'https://learn.microsoft.com/powershell/' },
      { label: 'Linux man-pages project', url: 'https://www.kernel.org/doc/man-pages/' },
    ],
  },
  {
    id: 'it-devops',
    name: 'DevOps & IT Service Management',
    subtitle: 'CI/CD, Git, containers, ITIL',
    description: 'CI/CD pipelines, Git workflows, containers and orchestration basics, and ITIL/ITSM fundamentals.',
    examTotal: 20,
    passMark: 14,
    hasLanguages: false,
    hasImages: false,
    hasLawNotice: false,
    references: [
      { label: 'Docker official documentation', url: 'https://docs.docker.com/' },
      { label: 'Kubernetes official documentation', url: 'https://kubernetes.io/docs/home/' },
      { label: 'Git official documentation', url: 'https://git-scm.com/doc' },
      { label: 'ITIL 4 overview (AXELOS / PeopleCert)', url: 'https://www.peoplecert.org/products/itil-4-foundation' },
    ],
  },
]

export function getTrack(trackId) {
  return TRACKS.find((t) => t.id === trackId) || TRACKS[0]
}
